<?php

/**
 * @file
 * Contains os2forms_nemlogin_openid_connect.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\os2forms_nemlogin_openid_connect\Helper\WebformHelper;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_help().
 */
function os2forms_nemlogin_openid_connect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2forms_nemlogin_openid_connect module.
    case 'help.page.os2forms_nemlogin_openid_connect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('os2forms_nemlogin_openid_connect') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function os2forms_nemlogin_openid_connect_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service(WebformHelper::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function os2forms_nemlogin_openid_connect_webform_submission_prepare_form(WebformSubmissionInterface $webform_submission, string $operation, FormStateInterface $form_state) {
  Drupal::service(WebformHelper::class)->webformSubmissionPrepareForm($webform_submission, $operation, $form_state);
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function os2forms_nemlogin_openid_connect_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service(WebformHelper::class)->webformThirdPartySettingsFormAlter($form, $form_state);
}
