<?php

/**
 * @file
 * Contains os2forms_nemlogin_openid_connect.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\os2forms_nemlogin_openid_connect\Helper\Settings;
use Drupal\os2forms_nemlogin_openid_connect\Helper\WebformHelper;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_help().
 */
function os2forms_nemlogin_openid_connect_help(string $route_name, RouteMatchInterface $route_match): ?string {
  switch ($route_name) {
    // Main module help for the os2forms_nemlogin_openid_connect module.
    case 'help.page.os2forms_nemlogin_openid_connect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('os2forms_nemlogin_openid_connect') . '</p>';
      return $output;
  }

  return NULL;
}

/**
 * Implements hook_form_alter().
 *
 * @phpstan-param array<string, mixed> $form
 */
function os2forms_nemlogin_openid_connect_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  Drupal::service(WebformHelper::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_ENTITY_TYPE_prepare_form().
 */
function os2forms_nemlogin_openid_connect_webform_submission_prepare_form(WebformSubmissionInterface $webform_submission, string $operation, FormStateInterface $form_state): void {
  Drupal::service(WebformHelper::class)->webformSubmissionPrepareForm($webform_submission, $operation, $form_state);
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 *
 * @phpstan-param array<string, mixed> $form
 */
function os2forms_nemlogin_openid_connect_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  Drupal::service(WebformHelper::class)->webformThirdPartySettingsFormAlter($form, $form_state);
}

/**
 * Implements hook_theme().
 *
 * @phpstan-param array<string, mixed> $existing
 * @phpstan-return array<string, mixed>
 */
function os2forms_nemlogin_openid_connect_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'os2forms_nemlogin_openid_connect_local_test_users' => [
      'variables' => [
        'users' => NULL,
        'plugin' => NULL,
        'query' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_os2web_nemlogin_auth_provider_info_alter().
 */
function os2forms_nemlogin_openid_connect_os2web_nemlogin_auth_provider_info_alter(array &$definitions) {
  if (isset($definitions['OpenIDConnect'])) {
    $template = $definitions['OpenIDConnect'];
    unset($definitions['OpenIDConnect']);

    $providers = Drupal::service(Settings::class)->getProvidersAsArray();

    foreach ($providers as $id => $label) {
      $definitions[$id] = [
        'id' => $id,
        'label' => $label,
      ] + $template;
    }
  }
}
