<?php

/**
 * @file
 * Contains os2forms_nemlogin_openid_connect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function os2forms_nemlogin_openid_connect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2forms_nemlogin_openid_connect module.
    case 'help.page.os2forms_nemlogin_openid_connect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('os2forms_nemlogin_openid_connect') . '</p>';
      return $output;

    default:
  }
}
